### ISSUE TITLE
Kā būtu ar Ruby 2.0?

### ISSUE THREAD

**Issue by jacob-s-son** [dzintars-valoda/dzintars#1]
Varētu tikt vaļā no "#encoding: UTF-8".
Es varu mēģināt salabot, ja aktuāli.

**Comment by janjiss** [comment]
Protams ka aktuâli :)

2013/6/26 Edgars Jçkabsons notifications@github.com

**Comment by rsim** [comment]
Dzintara kodā jau nevajag rakstīt `# encoding: utf-8`, tas ir tikai uzģenerētajā Ruby kodā.

Tā ka manuprāt nevajag tikt vaļā, lai strādātu arī uz Ruby 1.9. Un bez tā komentāra bija problēmas, ka arī uz Ruby 2.0 ruby_parser gem neatpazina latviskos atslēgvārdus.

**Comment by jacob-s-son** [comment]
Es biju runājis  par "iekšējo" kodu. Tad šobrīd paliek 1.9 par bāzi ?

**Comment by rsim** [comment]
Es parasti cenšos gemos atbalstīt pēdējās divas Ruby bāzes versijas, tā ka būtu labi pagaidām gan Ruby 1.9.3, gan 2.0.0 atbalstīt.

Būtu labi sataisīt, lai testi uz travisci grieztos uz visām atbalstītajām Ruby versijām.

**Comment by torbjon** [comment]
Izdarīts: https://github.com/dzintars-valoda/dzintars/commit/b4f39f6173ca2f1f19634e3b6cde9ab3ad736c88
