### ISSUE TITLE
repozitorijs dzintars.web

### ISSUE THREAD

**Issue by torbjon** [dzintars-valoda/dzintars#8]
es izveidoju elementaru basic vebisko interpretatoru http://dzintars.herokuapp.com/ 

Raimonds, vai tu vari man iedod tiesibas izveidot repozitoriju ieksh https://github.com/dzintars-valoda vai izveido, dzintars-valoda.org repozitoriju un nosharo pieejas

es iepushoshu

**Comment by rsim** [comment]
Super, ka izveidoji webisko interpretatoru - bija doma, ka tādu vajadzētu :)
Kā tur ar drošības lietām - vai ar `eval "..."` neko sliktu nevar izdarīt?
Un būtu labi arī Ajaxisku uztaisīt, lai turpat blakus rādītu rezultātu.

Pieliku Tevi pie owners grupas, vajadzētu Tev varēt tagad izveidot jaunu repozitoriju.

**Comment by torbjon** [comment]
paldies, man

bija plani: ajax, ace.js ar dzintars sintaksi iezimeshanu un ntos piemerus, ja un platako lietotaju interfeisu ;)

par `eval` neesmu parliecinats, bet pacik tas heroku, vini ierobezos sava smilshkastite

https://github.com/dzintars-valoda/dzintars.web/blob/master/app.rb#L8-L12
